const cardInfo = [
  {
    id: '1',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Jenna Ortega',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/1.jpg',
    card_image: '',
  },
  {
    id: '2',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Garrett Winters',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/2.jpg',
    card_image: '',
  },
  {
    id: '3',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Ashton Cox',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/3.jpg',
    card_image: '',
  },
  {
    id: '4',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Cedric Kelly',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/4.jpg',
    card_image: '',
  },
  {
    id: '5',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Airi Satou',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/5.jpg',
    card_image: '',
  },
  {
    id: '6',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Brielle Williamson',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/6.jpg',
    card_image: '',
  },
  {
    id: '7',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Herrod Chandler',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/7.jpg',
    card_image: '',
  },
  {
    id: '8',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Rhona Davidson',
    title: 'Big 4 Auditor Financial Analyst',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/8.jpg',
    card_image: '',
  },
  {
    id: '9',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Colleen Hurst',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/9.jpg',
    card_image: '',
  },
  {
    id: '10',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Sonya Frost',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/10.jpg',
    card_image: '',
  },
  {
    id: '11',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Jena Gaines',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/11.jpg',
    card_image: '',
  },
  {
    id: '12',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Quinn Flynn',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/12.jpg',
    card_image: '',
  },
  {
    id: '13',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Charde Marshall',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/12.jpg',
    card_image: '',
  },
  {
    id: '14',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Haley Kennedy',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/14.jpg',
    card_image: '',
  },
  {
    id: '15',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Tatyana Fitzpatrick',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/15.jpg',
    card_image: '',
  },
  {
    id: '16',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Michael Silva',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/16.jpg',
    card_image: '',
  },
  {
    id: '17',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Paul Byrd',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/17.jpg',
    card_image: '',
  },
  {
    id: '18',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Gloria Little',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/18.jpg',
    card_image: '',
  },
  {
    id: '19',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Bradley Greer',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/19.jpg',
    card_image: '',
  },
  {
    id: '20',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Dai Rios',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/20.jpg',
    card_image: '',
  },
  {
    id: '21',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Jenette Caldwell',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/21.jpg',
    card_image: '',
  },
  {
    id: '22',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Yuri Berry',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/22.jpg',
    card_image: '',
  },
  {
    id: '23',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Caesar Vance',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/men/23.jpg',
    card_image: '',
  },
  {
    id: '24',
    title: 'Big 4 Auditor Financial Analyst',
    instructor_name: 'Doris Wilder',
    course_price: '300000',
    instructor_profession: 'Senior Accountant',
    profile_image: 'https://randomuser.me/api/portraits/women/24.jpg',
    card_image: '',
  },
];
